module.exports = {
  extends: ['stylelint-prettier/recommended'],
  plugins: [
    'stylelint-order',
    'stylelint-scss'
  ],
  rules: {
    'at-rule-disallowed-list': ['debug'],
    'at-rule-no-unknown': null,
    'at-rule-no-vendor-prefix': true,
    'block-no-empty': true,
    'block-opening-brace-space-before': 'always',
    'color-hex-case': 'lower',
    'color-hex-length': 'long',
    'color-named': 'never',
    'color-no-invalid-hex': true,
    'declaration-bang-space-after': 'never',
    'declaration-bang-space-before': 'always',
    'declaration-block-semicolon-newline-after': 'always',
    'declaration-block-semicolon-space-before': 'never',
    'declaration-block-single-line-max-declarations': 1,
    'declaration-block-trailing-semicolon': 'always',
    'declaration-colon-space-after': 'always-single-line',
    'declaration-colon-space-before': 'never',
    'declaration-property-value-disallowed-list': {
      'border': ['none'],
      'border-top': ['none'],
      'border-right': ['none'],
      'border-bottom': ['none'],
      'border-left': ['none']
    },
    'function-comma-space-after': 'always-single-line',
    'function-parentheses-space-inside': 'never',
    'function-url-quotes': 'always',
    'indentation': 2,
    'length-zero-no-unit': true,
    'max-nesting-depth': [
      1,
      {
        'ignoreAtRules': [
          'each',
          'media',
          'supports',
          'include'
        ]
      }
    ],
    'media-feature-name-no-vendor-prefix': true,
    'media-feature-parentheses-space-inside': 'never',
    'no-missing-end-of-source-newline': true,
    'number-leading-zero': 'always',
    'number-no-trailing-zeros': true,
    'order/order': [
      [
        'custom-properties',
        'dollar-variables',
        {
          'type': 'at-rule',
          'name': 'extend'
        },
        {
          'type': 'at-rule',
          'name': 'include',
          'hasBlock': false
        },
        'declarations',
        {
          'type': 'at-rule',
          'name': 'include',
          'hasBlock': true
        },
        'rules'
      ]
    ],
    'order/properties-order': [
      'content',
      'position',
      'top',
      'right',
      'bottom',
      'left',
      'z-index',
      'display',
      '-webkit-flex',
      '-ms-flex',
      'flex',
      '-webkit-flex-grow',
      'flex-grow',
      '-webkit-flex-shrink',
      'flex-shrink',
      '-webkit-flex-basis',
      'flex-basis',
      '-webkit-flex-flow',
      'flex-flow',
      '-webkit-flex-direction',
      '-ms-flex-direction',
      'flex-direction',
      '-webkit-flex-wrap',
      'flex-wrap',
      '-webkit-justify-content',
      'justify-content',
      '-webkit-align-content',
      'align-content',
      '-webkit-align-items',
      'align-items',
      '-webkit-order',
      '-ms-flex-order',
      'order',
      '-ms-grid-row-align',
      '-webkit-align-self',
      'align-self',
      '-ms-grid-column-align',
      'justify-self',
      'grid',
      'grid-area',
      'grid-auto-columns',
      'grid-auto-flow',
      'grid-auto-rows',
      'grid-column',
      'grid-column-end',
      '-ms-grid-column-span',
      'grid-column-gap',
      '-ms-grid-column',
      'grid-column-start',
      'grid-gap',
      'grid-row',
      'grid-row-end',
      '-ms-grid-row-span',
      'grid-row-gap',
      '-ms-grid-row',
      'grid-row-start',
      'grid-template',
      'grid-template-areas',
      '-ms-grid-columns',
      'grid-template-columns',
      '-ms-grid-rows',
      'grid-template-rows',
      'float',
      'clear',
      '-webkit-box-sizing',
      '-moz-box-sizing',
      'box-sizing',
      'width',
      'min-width',
      'max-width',
      'height',
      'min-height',
      'max-height',
      'margin',
      'margin-top',
      'margin-right',
      'margin-bottom',
      'margin-left',
      'padding',
      'padding-top',
      'padding-right',
      'padding-bottom',
      'padding-left',
      'overflow',
      '-ms-overflow-x',
      'overflow-x',
      '-ms-overflow-y',
      'overflow-y',
      '-webkit-overflow-scrolling',
      '-ms-overflow-style',
      'list-style',
      'list-style-position',
      'list-style-type',
      'list-style-image',
      'border-collapse',
      'border-spacing',
      'table-layout',
      'empty-cells',
      'caption-side',
      'font',
      'font-weight',
      'font-size',
      'line-height',
      'font-family',
      'vertical-align',
      'text-align',
      'direction',
      'color',
      'text-transform',
      'text-decoration',
      'font-style',
      'font-variant',
      'font-size-adjust',
      'font-stretch',
      'font-effect',
      'font-emphasize',
      'font-emphasize-position',
      'font-emphasize-style',
      '-webkit-font-smoothing',
      '-moz-osx-font-smoothing',
      'font-smooth',
      '-webkit-text-align-last',
      '-moz-text-align-last',
      '-ms-text-align-last',
      'text-align-last',
      'letter-spacing',
      'word-spacing',
      'white-space',
      'text-emphasis',
      'text-emphasis-color',
      'text-emphasis-style',
      'text-emphasis-position',
      'text-indent',
      '-ms-text-justify',
      'text-justify',
      '-ms-writing-mode',
      'text-outline',
      'text-wrap',
      '-ms-text-overflow',
      'text-overflow',
      'text-overflow-ellipsis',
      'text-overflow-mode',
      'text-orientation',
      '-ms-word-wrap',
      'word-wrap',
      '-ms-word-break',
      'word-break',
      '-moz-tab-size',
      '-o-tab-size',
      'overflow-wrap',
      'tab-size',
      '-webkit-hyphens',
      '-moz-hyphens',
      'hyphens',
      'unicode-bidi',
      'columns',
      'column-count',
      'column-fill',
      'column-gap',
      'column-rule',
      'column-rule-color',
      'column-rule-style',
      'column-rule-width',
      'column-span',
      'column-width',
      'text-shadow',
      'page-break-after',
      'page-break-before',
      'page-break-inside',
      'src',
      'background',
      'background-color',
      'background-image',
      'background-repeat',
      'background-position',
      '-ms-background-position-x',
      'background-position-x',
      '-ms-background-position-y',
      'background-position-y',
      '-webkit-background-size',
      '-moz-background-size',
      '-o-background-size',
      'background-size',
      '-webkit-background-clip',
      '-moz-background-clip',
      'background-clip',
      'background-origin',
      'background-attachment',
      'box-decoration-break',
      'background-blend-mode',
      'border',
      'border-width',
      'border-style',
      'border-color',
      'border-top',
      'border-top-width',
      'border-top-style',
      'border-top-color',
      'border-right',
      'border-right-width',
      'border-right-style',
      'border-right-color',
      'border-bottom',
      'border-bottom-width',
      'border-bottom-style',
      'border-bottom-color',
      'border-left',
      'border-left-width',
      'border-left-style',
      'border-left-color',
      '-webkit-border-radius',
      '-moz-border-radius',
      'border-radius',
      '-webkit-border-top-left-radius',
      '-moz-border-radius-topleft',
      'border-top-left-radius',
      '-webkit-border-top-right-radius',
      '-moz-border-radius-topright',
      'border-top-right-radius',
      '-webkit-border-bottom-right-radius',
      '-moz-border-radius-bottomright',
      'border-bottom-right-radius',
      '-webkit-border-bottom-left-radius',
      '-moz-border-radius-bottomleft',
      'border-bottom-left-radius',
      '-webkit-border-image',
      '-moz-border-image',
      '-o-border-image',
      'border-image',
      '-webkit-border-image-source',
      '-moz-border-image-source',
      '-o-border-image-source',
      'border-image-source',
      '-webkit-border-image-slice',
      '-moz-border-image-slice',
      '-o-border-image-slice',
      'border-image-slice',
      '-webkit-border-image-width',
      '-moz-border-image-width',
      '-o-border-image-width',
      'border-image-width',
      '-webkit-border-image-outset',
      '-moz-border-image-outset',
      '-o-border-image-outset',
      'border-image-outset',
      '-webkit-border-image-repeat',
      '-moz-border-image-repeat',
      '-o-border-image-repeat',
      'border-image-repeat',
      'outline',
      'outline-width',
      'outline-style',
      'outline-color',
      'outline-offset',
      '-webkit-box-shadow',
      '-moz-box-shadow',
      'box-shadow',
      '-webkit-transform',
      '-moz-transform',
      '-ms-transform',
      '-o-transform',
      'transform',
      '-webkit-transform-origin',
      '-moz-transform-origin',
      '-ms-transform-origin',
      '-o-transform-origin',
      'transform-origin',
      '-webkit-backface-visibility',
      '-moz-backface-visibility',
      'backface-visibility',
      '-webkit-perspective',
      '-moz-perspective',
      'perspective',
      '-webkit-perspective-origin',
      '-moz-perspective-origin',
      'perspective-origin',
      '-webkit-transform-style',
      '-moz-transform-style',
      'transform-style',
      'visibility',
      'cursor',
      'opacity',
      'interpolation-mode',
      '-webkit-filter',
      'filter',
      'backdrop-filter',
      '-webkit-transition',
      '-moz-transition',
      '-ms-transition',
      '-o-transition',
      'transition',
      '-webkit-transition-delay',
      '-moz-transition-delay',
      '-ms-transition-delay',
      '-o-transition-delay',
      'transition-delay',
      '-webkit-transition-timing-function',
      '-moz-transition-timing-function',
      '-ms-transition-timing-function',
      '-o-transition-timing-function',
      'transition-timing-function',
      '-webkit-transition-duration',
      '-moz-transition-duration',
      '-ms-transition-duration',
      '-o-transition-duration',
      'transition-duration',
      '-webkit-transition-property',
      '-moz-transition-property',
      '-ms-transition-property',
      '-o-transition-property',
      'transition-property',
      '-webkit-animation',
      '-moz-animation',
      '-ms-animation',
      '-o-animation',
      'animation',
      '-webkit-animation-name',
      '-moz-animation-name',
      '-ms-animation-name',
      '-o-animation-name',
      'animation-name',
      '-webkit-animation-duration',
      '-moz-animation-duration',
      '-ms-animation-duration',
      '-o-animation-duration',
      'animation-duration',
      '-webkit-animation-play-state',
      '-moz-animation-play-state',
      '-ms-animation-play-state',
      '-o-animation-play-state',
      'animation-play-state',
      '-webkit-animation-timing-function',
      '-moz-animation-timing-function',
      '-ms-animation-timing-function',
      '-o-animation-timing-function',
      'animation-timing-function',
      '-webkit-animation-delay',
      '-moz-animation-delay',
      '-ms-animation-delay',
      '-o-animation-delay',
      'animation-delay',
      '-webkit-animation-iteration-count',
      '-moz-animation-iteration-count',
      '-ms-animation-iteration-count',
      '-o-animation-iteration-count',
      'animation-iteration-count',
      '-webkit-animation-direction',
      '-moz-animation-direction',
      '-ms-animation-direction',
      '-o-animation-direction',
      'animation-direction',
      '-webkit-animation-fill-mode',
      '-moz-animation-fill-mode',
      '-ms-animation-fill-mode',
      '-o-animation-fill-mode',
      'animation-fill-mode',
      'appearance',
      'clip',
      'clip-path',
      'counter-reset',
      'counter-increment',
      'resize',
      '-webkit-user-select',
      '-moz-user-select',
      '-ms-user-select',
      'user-select',
      '-webkit-tap-highlight-color',
      'nav-index',
      'nav-up',
      'nav-right',
      'nav-down',
      'nav-left',
      'pointer-events',
      'quotes',
      'touch-action',
      'will-change',
      'zoom',
      'fill',
      'fill-rule',
      'clip-rule',
      'stroke'
    ],
    'property-no-unknown': true,
    'property-no-vendor-prefix': true,
    'rule-empty-line-before': [
      'always-multi-line',
      {
        'except': ['first-nested'],
        'ignore': ['after-comment']
      }
    ],
    'scss/at-extend-no-missing-placeholder': true,
    'scss/at-function-pattern': '^[a-z]+([a-z0-9-]+[a-z0-9]+)?$',
    'scss/at-import-no-partial-leading-underscore': true,
    'scss/at-import-partial-extension-blacklist': ['scss'],
    'scss/at-mixin-pattern': '^[a-z]+([a-z0-9-]+[a-z0-9]+)?$',
    'scss/at-rule-no-unknown': true,
    'scss/dollar-variable-colon-space-after': 'always',
    'scss/dollar-variable-colon-space-before': 'never',
    'scss/dollar-variable-pattern': '^[_]?[a-z]+([a-z0-9-]+[a-z0-9]+)?$',
    'scss/percent-placeholder-pattern': '^[a-z]+([a-z0-9-]+[a-z0-9]+)?$',
    'scss/selector-no-redundant-nesting-selector': true,
    'selector-class-pattern': [
      '^[a-z0-9\\-]+$',
      {
        'message':
        'Selector should be written in lowercase with hyphens (selector-class-pattern)'
      }
    ],
    'selector-list-comma-newline-after': 'always',
    'selector-max-compound-selectors': 3,
    'selector-max-id': 0,
    'selector-no-qualifying-type': true,
    'selector-no-vendor-prefix': true,
    'selector-pseudo-element-colon-notation': 'double',
    'selector-pseudo-element-no-unknown': true,
    'shorthand-property-no-redundant-values': true,
    'string-quotes': 'single',
    'value-no-vendor-prefix': true
  }
}
